/**
Creating Database and tables for an example Library System
**/

CREATE DATABASE db_librarysystem
USE db_librarysystem

CREATE TABLE lib_library_branch (
	BranchID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	BranchName VARCHAR(30) NOT NULL,
	BranchAddress VARCHAR(150) NOT NULL
	)

CREATE TABLE lib_publisher (
	PublisherID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	PublisherName VARCHAR(50) NOT NULL,
	PublisherAddress VARCHAR(150) NOT NULL,
	PublisherPhone VARCHAR(15)
	)

CREATE TABLE lib_book_author (
	AuthorID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	AuthorName VARCHAR(50) NOT NULL
	)

CREATE TABLE lib_borrower (
	BorrowerID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	BorrowerName VARCHAR(50) NOT NULL,
	BorrowerAddress VARCHAR(150) NOT NULL,
	BorrowerPhone VARCHAR(15) NOT NULL
	)

CREATE TABLE lib_books (
	BookID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	BookTitle VARCHAR(100) NOT NULL,
	AuthorID INT NOT NULL CONSTRAINT fk_author FOREIGN KEY REFERENCES lib_book_author(AuthorID) ON UPDATE CASCADE ON DELETE CASCADE,
	PublisherID INT NOT NULL CONSTRAINT fk_publisher FOREIGN KEY REFERENCES lib_publisher(PublisherID) ON UPDATE CASCADE ON DELETE CASCADE
	)

CREATE TABLE lib_bookcopies (
	BookCopyID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	BookID INT NOT NULL CONSTRAINT fk_book FOREIGN KEY REFERENCES lib_books(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT NOT NULL CONSTRAINT fk_branch FOREIGN KEY REFERENCES lib_library_branch(BranchID) ON UPDATE CASCADE ON DELETE CASCADE
	)

CREATE TABLE lib_bookloans (
	LoanID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	BookCopyID INT NOT NULL CONSTRAINT fk_bookcopy FOREIGN KEY REFERENCES lib_bookcopies(BookCopyID) ON UPDATE CASCADE ON DELETE CASCADE,
	BorrowerID INT NOT NULL CONSTRAINT fk_borrower FOREIGN KEY REFERENCES lib_borrower(BorrowerID) ON UPDATE CASCADE ON DELETE CASCADE,
	DateOut DATETIME NOT NULL,
	DateDue DATE NOT NULL
	)